### ISSUE TITLE
有些公式乱码了也

### ISSUE THREAD

**Issue by gravitychen** [CatOnly/CrashNote#1]
如题

**Comment by yd7am** [comment]
自己改了，不过总结的挺好的，也给了我些新收获。

**Comment by CatOnly** [comment]
> 如题

用 Typora 这个软件也会乱码么？我只在这个软件上写和看
如果是，发一下乱码的字符串也行

**Comment by CatOnly** [comment]
@gravitychen 是在 Typora 这个软件里乱码的么？如果是，发下乱码的字符串我看看，我不考虑其他软件的体验

@yd7am 感谢，请多指出文章的目录结构或细节上的不足，最好附上引用连接

**Comment by Euynac** [comment]
确实有些公式在Typora没有自动格式化，使用的版本是0.9.96最新版，形如$|v| = \sqrt{x^2 + y^2 +z^2}$的公式（开头是$结尾是$）还是原样显示。比如Part0_Base1.3向量的基（单位向量）向量的长度（向量的模）：$|v| = \sqrt{x^2 + y^2 +z^2}$

**Comment by CatOnly** [comment]
> 确实有些公式在Typora没有自动格式化，使用的版本是0.9.96最新版，形如$|v| = \sqrt{x^2 + y^2 +z^2}$的公式（开头是$结尾是$）还是原样显示。比如Part0_Base1.3向量的基（单位向量）向量的长度（向量的模）：$|v| = \sqrt{x^2 + y^2 +z^2}$

嗯 Typora 的问题，这种情况，一般重新在公式打个空格，在最后一行打个回车就好了

**Comment by devxzh** [comment]
打开偏好设置 -> Markdown -> markdown 扩展语法 全打勾，重启就可以了
